name: balkhash_taste
description: "Balkhash Taste App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # 👉 ЛОКАЛИЗАЦИЯ (добавили)
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3

  # Firebase
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # 👉 ВКЛЮЧАЕМ генерацию локализации
  generate: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/icon/instagram.png
    - assets/icon/2gis.png
    - assets/icon/phone.png


# ---------------- ICON ----------------
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#07110D"
  adaptive_icon_foreground: "assets/icon/app_icon.png"