// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLWS0X_0hc0eGMS--E8DK631Gdyu7Jq7I',
    appId: '1:476466769685:web:52ee9685bd939435ba431c',
    messagingSenderId: '476466769685',
    projectId: 'balkhash-taste-a5fb9',
    authDomain: 'balkhash-taste-a5fb9.firebaseapp.com',
    storageBucket: 'balkhash-taste-a5fb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgQbjzCAbBM72zn0Sk4QaQjAj5Q3KHSxU',
    appId: '1:476466769685:android:e588915b345a1461ba431c',
    messagingSenderId: '476466769685',
    projectId: 'balkhash-taste-a5fb9',
    storageBucket: 'balkhash-taste-a5fb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdk_kIGfNhZyYVAfsRIKOUa9yjd5wzW38',
    appId: '1:476466769685:ios:d8f7f48c295ce717ba431c',
    messagingSenderId: '476466769685',
    projectId: 'balkhash-taste-a5fb9',
    storageBucket: 'balkhash-taste-a5fb9.firebasestorage.app',
    iosBundleId: 'com.example.balkhashTaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdk_kIGfNhZyYVAfsRIKOUa9yjd5wzW38',
    appId: '1:476466769685:ios:d8f7f48c295ce717ba431c',
    messagingSenderId: '476466769685',
    projectId: 'balkhash-taste-a5fb9',
    storageBucket: 'balkhash-taste-a5fb9.firebasestorage.app',
    iosBundleId: 'com.example.balkhashTaste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLWS0X_0hc0eGMS--E8DK631Gdyu7Jq7I',
    appId: '1:476466769685:web:58befcfd5b22f353ba431c',
    messagingSenderId: '476466769685',
    projectId: 'balkhash-taste-a5fb9',
    authDomain: 'balkhash-taste-a5fb9.firebaseapp.com',
    storageBucket: 'balkhash-taste-a5fb9.firebasestorage.app',
  );
}
